### ISSUE TITLE
2.0.4版本严重问题

### ISSUE THREAD

**Issue by abccyz** [battcn/swagger-spring-boot#10]
- 调试接口的请求地址是错误的 拼接结果是swagger-ui.html/xxx/xxx导致不能正常使用调试接口
- 示例：
 http://http//127.0.0.1/swagger-ui.html/api/v1/classroom?classroomId=&userId=0

**Comment by levin950825** [comment]
每太明白你的意思，samples 中是正常的，如果可以是否提供代码供我参考？

**Comment by abccyz** [comment]
找到问题了   你的这个发送测试请求的地方读取了配置中的host   我把配置中的host加上了http://xxxx.xxx/swagger-ui.html  你的程序中会出现 如上问题

**Comment by abccyz** [comment]
例如配置成这样的就会出问题：
![image](https://user-images.githubusercontent.com/6835596/43065366-308e339c-8e94-11e8-98e1-30a00b66ad17.png)

**Comment by levin950825** [comment]
明白了，这个BUG不算严重，先暂时不用该配置项就好了，我会在下个版本进行修复，谢谢你的指出

**Comment by levin950825** [comment]
这个问题在2.0.5已经得到修复，你可以自行下载代码install 到本地仓库，也可以等待  maven 中央仓库同步
