### ISSUE TITLE
@EnableAdminServer和swagger一起开启的时候,swagger无法访问

### ISSUE THREAD

**Issue by accpay219** [battcn/swagger-spring-boot#11]
![image](https://user-images.githubusercontent.com/16864100/43065531-b9a4c308-8e94-11e8-98d2-8a5c3a63849a.png)注释掉@EnableAdminServer,swagger就可以访问了这是为啥啊

**Comment by accpay219** [comment]
加上@EnableAdminServer访问swagger报404 , 开启过SBA security

**Comment by levin950825** [comment]
那你需要放开这几个路径

**Comment by levin950825** [comment]
那你需要放开这几个路径

**Comment by hh80c51** [comment]
同问，我这也是这样

**Comment by hh80c51** [comment]
> 

放开哪几个路径
