### ISSUE TITLE
2.0.6 如果编辑 json 会导致 json 加一个双引号传输

### ISSUE THREAD

**Issue by kiwiflydream** [battcn/swagger-spring-boot#15]
![图1](http://ww1.sinaimg.cn/large/68f7efe0gy1fty1bw5mwyj217y0dsdgq.jpg)

![图2](http://ww1.sinaimg.cn/large/68f7efe0gy1fty1c6vsv6j21am06kaaq.jpg)

如图1，json 的格式，如果我想改变参数，比如把0删除，想换一个数，网页会把文本域变成一个输入框，如图2所示。然后服务端接收的字符被加了一对双引号，然后因为最外层的双引号，服务器无法转换

**Comment by levin950825** [comment]
请提供相关代码块

**Comment by levin950825** [comment]
或者 QQ（1837307557） 联系我 细聊 方便我定位问题和解决

**Comment by kiwiflydream** [comment]
这个跟代码没关系吧，是不是前端页面做了什么事件，把短的字符串从textarea变成 input 输入。

**Comment by levin950825** [comment]
我想先明白这是 GET 还是 POST 才能取找对应代码块问题

**Comment by levin950825** [comment]
谢谢你的反馈，该ISSUES 已在 2.0.7-RELEASE 得到修改 并于今日发布
