### ISSUE TITLE
store/index.js中获取rootPath有问题

### ISSUE THREAD

**Issue by kingour** [battcn/swagger-spring-boot#18]
比如我的rootPath本来是/api/v1
通过页面http://localhost:8080/api/v1/swagger-ui.html后js获取的rootPath
变成了`http://localhost:8080/api`
然后他请求后台api全漏掉v1了

**Comment by levin950825** [comment]
如果您已解决可以试着提交PR   非常感谢

**Comment by abccyz** [comment]
主界面  能否美化下

**Comment by levin950825** [comment]
@abccyz    你能否帮助设计下UI 图  如果好，可以提供实现
