### ISSUE TITLE
看不到接口列表，同时报404错误

### ISSUE THREAD

**Issue by PiedPiperr** [battcn/swagger-spring-boot#2]
![20180613174654](https://user-images.githubusercontent.com/32378929/41343686-d298ad48-6f31-11e8-8af4-24d5544ca927.png)

**Comment by levin950825** [comment]
是否使用 @EnableSwagger2Doc 注解  是否配置了 spring.swagger.enable=true  如果前两步骤都满足，F12 看下错误信息

**Comment by PiedPiperr** [comment]
@levin950825  谢谢，没有在启动类上加@enableswagger2doc造成的。我以为不需要加这些了呢。
另外左侧栏列表看起来有点“挤”
![image](https://user-images.githubusercontent.com/32378929/41344648-394daf96-6f34-11e8-91ce-d125ac6c1780.png)

**Comment by levin950825** [comment]
`@Api(value = "用户接口", description = "用户接口", tags = {"1.1.0"})`

**Comment by levin950825** [comment]
如果 Api 注解不写完整 默认用的 Controller 名字 所以会溢出
