### ISSUE TITLE
任意密码可以登录

### ISSUE THREAD

**Issue by tinze** [battcn/swagger-spring-boot#20]
打开http://localhost:8080/swagger-ui.html 页面，不输入账号密码直接点击登录按钮，结果返回401，重新开一个窗口打开同样的页面，直接登录进来了

**Comment by levin950825** [comment]
谢谢你的使用反馈，已知晓，下个版本会修复改ISSUE

**Comment by levin950825** [comment]
`2.0.9-RELEASE` 已经修复当前ISSUE ，感谢您在使用过程反馈的意见，谢谢！
