### ISSUE TITLE
关于io.swagger.annotations.ApiModelProperty#required 属性的问题

### ISSUE THREAD

**Issue by 1397649957** [battcn/swagger-spring-boot#22]
![image](https://user-images.githubusercontent.com/35563513/45673759-2234b680-bb5e-11e8-9102-3a2cbc572599.png)
![image](https://user-images.githubusercontent.com/35563513/45673791-38db0d80-bb5e-11e8-9dc3-dcf9cc5f502b.png)
如果接口的参数是个对象，那么io.swagger.annotations.ApiModelProperty#required属性的true和false不会显示在请求参数的后面，试想有的时候一个对象里面的所有参数有些是可选的有些是必填的

**Comment by levin950825** [comment]
好的，我们会在近期发布，细节我们会持续更近  
PS：非内网情况记得配置开关哦

**Comment by 1397649957** [comment]
建议先将所类的属性后面的（是否必须）默认为一个值，true或者false，最好可以在类上面全局配置，因为有的时候一个类的大部分字段是必须传递的，也有时候大部分字段不是必须传递的，所以可以配置可能会好点，然后通过io.swagger.annotations.ApiModelProperty#required进行覆盖。感觉这样体验比较好🙃

**Comment by levin950825** [comment]
`2.0.9-RELEASE` 已经修复当前ISSUE ，感谢您在使用过程反馈的意见，谢谢！

**Comment by levin950825** [comment]
`2.1.0-RELEASE` 已经修复当前ISSUE ，感谢您在使用过程反馈的意见，谢谢！
