### ISSUE TITLE
2.1.0版本返回树形结构数据时,会导致该接口无法展示

### ISSUE THREAD

**Issue by hongsir** [battcn/swagger-spring-boot#23]
![](https://images.gitee.com/uploads/images/2018/1012/095914_d4b9bd58_733270.png)

![](https://images.gitee.com/uploads/images/2018/1012/100145_74546472_733270.png)

![](https://images.gitee.com/uploads/images/2018/1012/100321_2027a592_733270.png)

**Comment by levin950825** [comment]
`2.1.1-RELEASE` 已发布，如有需要可以更新版本，此BUG已在新版本得以修复，期待你的使用和反馈
