### ISSUE TITLE
@ApiImplicitParam参数 dataType = "Integer" 显示的时候 为 ref

### ISSUE THREAD

**Issue by TommyFreya** [battcn/swagger-spring-boot#25]
@ApiImplicitParam参数 dataType = "Integer" 显示的时候 为 ref,输入dataType = "int"的时候,界面反而会显示成integer

**Comment by levin950825** [comment]
谢谢你的反馈，该问题我们会在下个版本修复

**Comment by levin950825** [comment]
经过测试，`swagger` 的 `@ApiImplicitParam` 注解暂不支持 `Integer` 类型，这个得等 `io.swagger` 支持才行
