### ISSUE TITLE
调试接口界面中 请求参数值可以添加 @ApiModelProperty注解中example配置的默认值吗？

### ISSUE THREAD

**Issue by wcp1230** [battcn/swagger-spring-boot#27]
调试接口界面中 请求参数值可以添加 @ApiModelProperty注解中example配置的默认值吗？
现在在线调试界面中请求参数值都为空。

**Comment by levin950825** [comment]
很高兴收到您的反馈，已经确定，我们将在下一个版本进行修复

**Comment by levin950825** [comment]
您好，`2.1.2-RELEASE` 已发布到 `nexus` 国内同步需要 5-8 小时，如较急可以自行fork代码然后直接 `mvn install` 即可

**Comment by wcp1230** [comment]
ok，已确认显示处理了
