### ISSUE TITLE
请求参数为JSONObject时 没有按json传输  老版本可以

### ISSUE THREAD

**Issue by Fyuxuan** [battcn/swagger-spring-boot#28]
![image](https://user-images.githubusercontent.com/12712060/48396236-ba14e200-e754-11e8-9c1d-0c3a8167b1f1.png)

![image](https://user-images.githubusercontent.com/12712060/48396268-cd27b200-e754-11e8-81f1-d918aa997c21.png)

![image](https://user-images.githubusercontent.com/12712060/48396328-f7796f80-e754-11e8-9d16-2bfee66d1f84.png)

![image](https://user-images.githubusercontent.com/12712060/48396483-8be3d200-e755-11e8-8d20-16bd15ded532.png)

**Comment by levin950825** [comment]
去掉`@ApiParam`

**Comment by Fyuxuan** [comment]
@levin950825  你好 老哥  去掉了 还是不行 
![image](https://user-images.githubusercontent.com/12712060/48396761-7c18bd80-e756-11e8-8c65-ee6f558ae912.png)

![image](https://user-images.githubusercontent.com/12712060/48396799-9783c880-e756-11e8-835e-8fc4e3d15937.png)

**Comment by levin950825** [comment]
谢谢您的反馈，我们已经知晓，该问题是当前版本的`BUG`，我们将在下一个版本进行修复 ，当前版本只好通过 `POJO` 的方式使用

**Comment by Fyuxuan** [comment]
好的 峰哥  那下个版本大概什么时候能发布哦   比较急  =,=

**Comment by levin950825** [comment]
最迟本周五，如有提前，我会在`ISSUE`进行通知

**Comment by Fyuxuan** [comment]
@levin950825   恩恩  好的  辛苦了

**Comment by levin950825** [comment]
您好，`2.1.2-RELEASE` 已发布到 `nexus` 国内同步需要 5-8 小时，如较急可以自行fork代码然后直接 `mvn install` 即可

**Comment by Fyuxuan** [comment]
@levin950825  项目已更新2.1.2-RELEASE 经测试 bug 修复了  灰常感谢  辛苦了

**Comment by levin950825** [comment]
很高兴帮助到您，使用期间有问题欢迎提交 `ISSUES `，我先关闭当它了
