### ISSUE TITLE
参数是java对象时，展示对象下的每个字段行是否给个颜色区分上下级

### ISSUE THREAD

**Issue by wcp1230** [battcn/swagger-spring-boot#30]
参数是java对象时，展示对象下的每个字段行是否给个颜色区分上下级。 像RAP的中那样的效果

**Comment by levin950825** [comment]
不太明白你说的意思，方便的话加我QQ `1837307557`  详细说下

**Comment by levin950825** [comment]
https://github.com/battcn/swagger-spring-boot/releases/tag/2.1.3-RELEASE
