### ISSUE TITLE
接口菜单css样式问题

### ISSUE THREAD

**Issue by wcp1230** [battcn/swagger-spring-boot#31]
.swagger-left {
    width: 21%;
    overflow: hidden auto;
    margin-top: 0;
    position: fixed;
    height: 100%;
    transition: all .2s;
}

代码 overflow: hidden auto;  导致没有滚动条了。

**Comment by levin950825** [comment]
https://github.com/battcn/swagger-spring-boot/releases/tag/2.1.3-RELEASE
