### ISSUE TITLE
关于 controller返回  R<T> T 里面 嵌套对象不解析问题

### ISSUE THREAD

**Issue by qjyoung** [battcn/swagger-spring-boot#33]
如果 我在controller 方法 上 返回  R<T> T 比如 指定 是 User 对象 里面 嵌套一个 UserDetail对象 ，swagger 文档 响应Model 里面 会直接 把 UserDetail  解析 成 一个 String ，像这样
<img width="568" alt="image" src="https://user-images.githubusercontent.com/25897599/49196158-d061a580-f3c4-11e8-9ead-680183354920.png">

而不是 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/25897599/49196130-adcf8c80-f3c4-11e8-8430-cbbdf4a25617.png">

如果 直接  返回 User 对象 里面 的 UserDetail 是可以成功 解析的 如下
<img width="504" alt="image" src="https://user-images.githubusercontent.com/25897599/49196209-0141da80-f3c5-11e8-9d14-d781322199e7.png">

请问这怎么解决？

**Comment by levin950825** [comment]
你可以考虑升级成`2.1.2-RELEASE`试试

**Comment by qjyoung** [comment]
好的我试试

**Comment by qjyoung** [comment]
解决了 升级到  2.1.2-RELEASE 就好了  ui也更简洁 清晰了，很棒！😘
