### ISSUE TITLE
新版ui没有缩进效果

### ISSUE THREAD

**Issue by kuangzuoqiang** [battcn/swagger-spring-boot#34]
![image](https://user-images.githubusercontent.com/3454045/49261734-6c031c80-f47e-11e8-8907-b026ba5c7e7e.png)

级联关系时，表格没有缩进效果

**Comment by levin950825** [comment]
下一版本就会加入对象缩进效果

**Comment by levin950825** [comment]
https://github.com/battcn/swagger-spring-boot/releases/tag/2.1.3-RELEASE
