### ISSUE TITLE
在线调试key-value

### ISSUE THREAD

**Issue by qjyoung** [battcn/swagger-spring-boot#35]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/25897599/49275335-f9159800-f4b5-11e8-891f-0166f307ba9f.png">

这个 在线调试 怎么设置 key-value 请求? 我发现默认都是 json请求

**Comment by levin950825** [comment]
GET请求的就是 K=V的结构，如果是POST PUT PATCH 这类你写过`RequestBody` 就是 JSON 调试，详情可以看 `swagger-spring-boot-samples/sample-basic` 下的示例

**Comment by qjyoung** [comment]
post接口 但是 我没用 RequestBody 注解，【在线调试】依然发的是json请求，导致controller 参数取不到

**Comment by levin950825** [comment]
看下你 controller 方法怎么写的，将代码块贴出来

**Comment by qjyoung** [comment]
![image](https://user-images.githubusercontent.com/25897599/49276727-43007d00-f4ba-11e8-9ded-7e1d981b6880.png)
知道了 这里 必须是 query才行

**Comment by levin950825** [comment]
你如果不关心中文描述的情况下，默认这样也是可以的，通过注解方式也可以达到同样效果
``` java
    @PostMapping("/test3")
    public String test3(String param1, String param2) {
        return param1 + param2;
    }
```

**Comment by qjyoung** [comment]
嗯 OK了
