### ISSUE TITLE
嵌套实体时@ApiModelProperty解析必填错误

### ISSUE THREAD

**Issue by Fyuxuan** [battcn/swagger-spring-boot#36]
![image](https://user-images.githubusercontent.com/12712060/49283666-4e10d880-f4cd-11e8-9ab3-681b3a38bf7f.png)

![image](https://user-images.githubusercontent.com/12712060/49284432-887b7500-f4cf-11e8-8ba5-0c5462af5239.png)

嵌套的实体 设置为true时,页面显示也是为false

**Comment by Fyuxuan** [comment]
@995269937  请问下 close的原因是什么吗?

**Comment by levin950825** [comment]
@Fyuxuan 误操作导致，已重新`Open`

**Comment by Fyuxuan** [comment]
@levin950825  好的  不知道是不是个bug  对了我用的是最新版

**Comment by levin950825** [comment]
是`BUG`，我们在处理，下一个版本更新的东西会比较多，所以相对比较慢

**Comment by levin950825** [comment]
https://github.com/battcn/swagger-spring-boot/releases/tag/2.1.3-RELEASE
