### ISSUE TITLE
升级到2.0.1后泛型返回值不再显示

### ISSUE THREAD

**Issue by kiwiflydream** [battcn/swagger-spring-boot#4]
- 2.01 显示如下：
![image](https://user-images.githubusercontent.com/13311001/41663396-eeff5622-74d5-11e8-8035-df7a15c36c19.png)

- 1.45显示如下：
![image](https://user-images.githubusercontent.com/13311001/41663587-5f0507aa-74d6-11e8-912d-8fddc00f3e8d.png)
![image](https://user-images.githubusercontent.com/13311001/41663685-990ca976-74d6-11e8-8ffb-f52840af9273.png)

- 问题：
1.  json没有格式化
2. 泛型data没有展示

**Comment by levin950825** [comment]
感谢你的反馈，我们将在下个版本修复

**Comment by levin950825** [comment]
2.0.2 已修复该问题

**Comment by xiaowang1314** [comment]
最新版本好像又有这个问题了
