### ISSUE TITLE
2.0.3 登录接口404

### ISSUE THREAD

**Issue by kiwiflydream** [battcn/swagger-spring-boot#7]
接口登录报如下错误

``` json
{"timestamp":"2018-07-13T05:59:49.947+0000","status":404,"error":"Not Found","message":"No message available","path":"/v2/swagger-login"}
```

另外是项目主页的文档有问题
![](http://ww1.sinaimg.cn/large/68f7efe0gy1ft87nptxqqj210s0t4adm.jpg)
应该少了一个d

**Comment by levin950825** [comment]
2.0.3 存在 content-path 问题 在修复，近期修复好就会发布了

**Comment by levin950825** [comment]
2.0.3 发布了 也修复该问题了

**Comment by kiwiflydream** [comment]
升级后还是404，不知道什么原因？

**Comment by levin950825** [comment]
升级后 直接访问 `swagger-ui.html` 如果配置了

**Comment by kiwiflydream** [comment]
登录页一直是没有问题的，是登录页的登录接口一直返回404，默认的登录接口是/v2/xxxx，直接访问/v2/xxx也是404，这是要配置的吗？或者有没有演示的demo，因为近几个版本变动很大

**Comment by levin950825** [comment]
[](https://github.com/battcn/swagger-spring-boot/blob/master/swagger-spring-boot-samples/swagger-spring-boot-sample-basic)

**Comment by levin950825** [comment]
[https://github.com/battcn/swagger-spring-boot/blob/master/swagger-spring-boot-samples/swagger-spring-boot-sample-basic](https://github.com/battcn/swagger-spring-boot/blob/master/swagger-spring-boot-samples/swagger-spring-boot-sample-basic)

**Comment by levin950825** [comment]
``` java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@ComponentScan({"com.battcn","com.example.demo"})
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

**Comment by kiwiflydream** [comment]
好的，谢谢
