### ISSUE TITLE
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'

### ISSUE THREAD

**Issue by fishinhouse** [battcn/swagger-spring-boot#8]
Hi，

     User class id field is Long，controller method
```
    @GetMapping("/{id}")
    @ApiOperation(value = "Search User")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "id", value = "User ID")
    })
	public User get(@PathVariable Long id){
        .....
    }
```

log:
> Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jul 20 18:53:46 CST 2018
There was an unexpected error (type=Bad Request, status=400).
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "swagger-ui.html"

**Comment by levin950825** [comment]
``` java
 @ApiImplicitParam(name = "id", value = "User ID", dataType = DataType.LONG, paramType = ParamType.PATH)
```
sample `https://github.com/battcn/swagger-spring-boot/blob/master/swagger-spring-boot-samples/swagger-spring-boot-sample-basic/`

**Comment by fishinhouse** [comment]
新版本已解决。

**Comment by BeeralingaAnimation** [comment]
Hey still are you facing the same issue ?

**Comment by yathiraju** [comment]
how to solve this issue

**Comment by TscharnigGmBH** [comment]
I don't know

**Comment by Goliar** [comment]
how ca i solve this problem?
